name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y fish
          chmod +x ./setup_tests.sh ./test.sh
          ./setup_tests.sh

      - name: Run tests
        run: ./test.sh
